### ISSUE TITLE
Points incorrectly identified as inside certain shapes

### ISSUE THREAD

**Issue by christophermanning** [mikolalysenko/robust-point-in-polygon#1]
First of all, thank you for writing this helpful piece of software. While trying it out, I noticed it wasn't returning the correct result in certain scenarios. I added these tests to the `test.js` file and they seem to be incorrectly identifying these points as inside the polygon. I tried a few tweaks to the code, but couldn't get it working. Any guidance for fixing this would be very helpful. Thank you.

```
  // triangle
  t.equals(inside([[1,1],[2,1],[2,2]], [1,2]), 1) // incorrectly returns -1

  // parallelogram
  t.equals(inside([[1,1],[1,2],[2,3],[2,2]], [1,3]), 1) // incorrectly returns -1
```

Test output:

```
TAP version 13
# (anonymous)
not ok 1 should be equal
  ---
    operator: equal
    expected: 1
    actual:   -1
    at: Test.<anonymous> (robust-point-in-polygon/test/test.js:7:5)
  ...
not ok 2 should be equal
  ---
    operator: equal
    expected: 1
    actual:   -1
    at: Test.<anonymous> (robust-point-in-polygon/test/test.js:10:5)
```

**Comment by mikolalysenko** [comment]
Thanks for the heads up, this is a serious problem.  I will try to solve this tomorrow.

**Comment by mikolalysenko** [comment]
Ok, took me a little longer to get around to it but it should be working now.
